class_name Flags
extends Object

const DEBUG_FPS = "DEBUG_FPS"
const DEBUG_ROPE = "DEBUG_ROPE"
const DEBUG_PLAYER_CONTROLS = "DEBUG_PLAYER_CONTROLS"
const DEBUG_OCEAN_PLANES = "DEBUG_OCEAN_PLANES"
const DEBUG_WATER_HEIGHT = "DEBUG_WATER_HEIGHT"
const DEBUG_WATER_RENDER_TIME = "DEBUG_WATER_RENDER_TIME"
const DEBUG_TIME = "DEBUG_TIME"
const DEBUG_OCEAN_SHADER_PARAMS = "DEBUG_OCEAN_SHADER_PARAMS"
const DEBUG_SIMULATION_GRIDS = "DEBUG_SIMULATION_GRIDS"
const DEBUG_DRAW_NO_DEPTH_TEST = "DEBUG_DRAW_NO_DEPTH_TEST"

static var flags: Array[String] = [
	DEBUG_FPS,
	DEBUG_ROPE,
#	DEBUG_SIMULATION_GRIDS,
#	DEBUG_WATER_RENDER_TIME,
#	DEBUG_OCEAN_SHADER_PARAMS,
#	DEBUG_PLAYER_CONTROLS,
#	DEBUG_WATER_HEIGHT,
	DEBUG_OCEAN_PLANES,
#	DEBUG_DRAW_NO_DEPTH_TEST
]

static func is_enabled(flag: String) -> bool:
	return flags.find(flag) != -1
